"""sending

Revision ID: ecfbca89dbbe
Revises: ab7232780383
Create Date: 2023-11-23 03:51:09.323455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecfbca89dbbe'
down_revision = 'ab7232780383'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bf_2_22nov', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'bf_2_22nov')
    # ### end Alembic commands ###
