"""init

Revision ID: ab7232780383
Revises: 
Create Date: 2023-11-22 19:21:35.015302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab7232780383'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('path', sa.String(length=256), nullable=False),
    sa.Column('telegram_id', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('path')
    )
    op.create_table('users',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('registration_date', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('chosen_combination', sa.Integer(), nullable=True),
    sa.Column('rune_day_step', sa.Integer(), nullable=False),
    sa.Column('got_2h_autosending', sa.TIMESTAMP(), nullable=True),
    sa.Column('got_24h_autosending', sa.TIMESTAMP(), nullable=True),
    sa.Column('got_48h_autosending', sa.TIMESTAMP(), nullable=True),
    sa.Column('bf_state', sa.String(length=64), nullable=True),
    sa.Column('bf_22nov', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('files')
    # ### end Alembic commands ###
