"""comment

Revision ID: c364db890673
Revises: ecfbca89dbbe
Create Date: 2024-02-29 01:52:10.308596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c364db890673'
down_revision = 'ecfbca89dbbe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('sending_29_feb', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'sending_29_feb')
    # ### end Alembic commands ###
