"""init

Revision ID: f46e369dfbb9
Revises: 02f12fb29f55
Create Date: 2024-04-04 06:35:51.516785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f46e369dfbb9'
down_revision = '02f12fb29f55'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('sending_4_april', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'sending_4_april')
    # ### end Alembic commands ###
