"""empty message

Revision ID: 86eb36e225e9
Revises: f46e369dfbb9
Create Date: 2024-04-24 13:57:45.147218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86eb36e225e9'
down_revision = 'f46e369dfbb9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('sending_24_april', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'sending_24_april')
    # ### end Alembic commands ###
