"""comment

Revision ID: 7453e8f28c13
Revises: c364db890673
Create Date: 2024-03-11 02:54:07.230626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7453e8f28c13'
down_revision = 'c364db890673'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('sending_10_march', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'sending_10_march')
    # ### end Alembic commands ###
